### ISSUE TITLE
GETOK Registration for LUCAS_TEST - loneil@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#198]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: LUCAS_TEST <br /> IDIR: loneil@idir <br /> Email: lucas.oneil@gov.bc.ca</p> <p><strong>User comments:</strong><br/>I want access

**Comment by loneil** [comment]
Rejected, I don't know this guy
