### ISSUE TITLE
GETOK Registration for PS_REG - jleach_o@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#202]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PS_REG <br /> IDIR: jleach_o@idir <br /> Email: jason.leach@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Platform Services registry will send email notifications (updates) those who request namespaces.

**Comment by loneil** [comment]
Waiting for @matthewhall78 to approve acronym

**Comment by matthewhall78** [comment]
No Acronym check required, as this is not an IITD managed app.  So, yes approved.   Perhaps we could ask for their Ministry in the request, then we would know whether an Acronym check is required or not.  (AGRI, ENV, FLNRO, MIRR, EMPR, CSNR, IITD)  CSNR and IITD are Divisions, CSNR is part of FLNRO, and IITD is part of ENV, but only for reporting purposes.

**Comment by loneil** [comment]
👍 
Approved and email sent back to jason.leach@gov.bc.ca 10:22am Sept3, 2020
