### ISSUE TITLE
GETOK Registration for EHS_MHSU - kaolsenm@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#204]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: EHS_MHSU <br /> IDIR: kaolsenm@idir <br /> Email: kendall.a.olsenmaier@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Requesting access to CHES service on behalf of MHSU team for EHS mental health applications.

**Comment by loneil** [comment]
Approved and email sent back to kendall.a.olsenmaier@gov.bc.ca Tue 2020-09-22 3:06 PM
