### ISSUE TITLE
GETOK Registration for FOUNDRY_MHSU - kaolsenm@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#207]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: FOUNDRY_MHSU <br /> IDIR: kaolsenm@idir <br /> Email: kendall.a.olsenmaier@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Requesting access to CHES service on behalf of MHSU for Foundry project (request 2 of 2)

**Comment by loneil** [comment]
Approved and responded to kendall.a.olsenmaier@gov.bc.ca Oct 10 1:30 pm
