### ISSUE TITLE
GETOK Registration for THEQ - kgillani@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#208]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: THEQ <br /> IDIR: kgillani@idir <br /> Email: karim.gillani@gov.bc.ca</p> <p><strong>User comments:</strong><br/>I have two different instances of the application running.  One for SBC and one for SDPR.  Should I have two separate keys?

**Comment by loneil** [comment]
Created **2** acronyms, THEQ_SBC and THEQ_SDPR. Responses emailed back to karim.gillani@gov.bc.ca Thu 2020-10-15 10:25 AM
