### ISSUE TITLE
GETOK Registration for THEQ_SBC - skariyil@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#209]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: THEQ_SBC <br /> IDIR: skariyil@idir <br /> Email: sumesh.p.kariyil@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Access granted to Sumesh on previously created THEQ_SBC acronym. Response emailed back to sumesh.p.kariyil@gov.bc.ca at Thu 2020-10-15 4:10 PM
