### ISSUE TITLE
GETOK Registration for CSB_SS - tsemple@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#210]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CSB_SS <br /> IDIR: tsemple@idir <br /> Email: travis8814@gmail.com</p> <p><strong>User comments:</strong><br/>This is for Court Services Branch - Sheriff Scheduling

**Comment by loneil** [comment]
Approved and responded via email to travis8814@gmail.com at Fri 2020-10-16 10:33 AM
