### ISSUE TITLE
GETOK Registration for CSB_SS - wbarnes@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#211]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CSB_SS <br /> IDIR: wbarnes@idir <br /> Email: wade.barnes@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Requesting team member access to the CSB_SS CHES account.

**Comment by loneil** [comment]
Access to CSB_SS added for Wade. Email responded Mon 2020-10-19 1:44 PM
