### ISSUE TITLE
GETOK Registration for ARCH_TEST - macarrig@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#213]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: ARCH_TEST <br /> IDIR: macarrig@idir <br /> Email: mary.carrigan@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Testing of process to add Archaeology Newsletters Mailout

**Comment by loneil** [comment]
Approved for **ARCH_NEWS** (don't want acronyms labeled as TEST), email sent back to mary.carrigan@gov.bc.ca at Monday, October 26, 2020 1:53:04 PM
