### ISSUE TITLE
GETOK Registration for ZEVA - kmenke@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#218]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: ZEVA <br /> IDIR: kmenke@idir <br /> Email: katie.menke@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Email sent back to katie.menke@gov.bc.ca Tue 2020-11-24 1:38 PM
