### ISSUE TITLE
GETOK Registration for MALS - kylmorel@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#221]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: MALS <br /> IDIR: kylmorel@idir <br /> Email: kmorel@parcsystems.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Email sent back to kmorel@parcsystems.ca _Tue 2020-12-01 10:16 AM_
