### ISSUE TITLE
GETOK Registration for FNCS - mjunkin@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#225]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: FNCS <br /> IDIR: mjunkin@idir <br /> Email: mjunkin@vividsolutions.com</p> <p><strong>User comments:</strong><br/>The First Nations Consultation System would like to use CDOGS to generate documents.

**Comment by loneil** [comment]
Emailed back to mjunkin@vividsolutions.com at  _Wed 2020-12-02 4:24 PM_
