### ISSUE TITLE
GETOK Registration for PS_REG - yfreeman@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#241]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PS_REG <br /> IDIR: yfreeman@idir <br /> Email: yuhan.freeman@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Require access on Jason Leach's direction.

**Comment by loneil** [comment]
Emailed back to yuhan.freeman@gov.bc.ca at _Wed 2020-12-23 11:17 AM_
