### ISSUE TITLE
GETOK Registration for PS_REG - sbathgat@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#242]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PS_REG <br /> IDIR: sbathgat@idir <br /> Email: shaun.bathgate@gov.bc.ca</p> <p><strong>User comments:</strong><br/>I am one of the developers for the Platform Services Registry. When we tried to add me to the project it informed us to request an account and your team can add me to it. Jason Leach is the senior developer in charge if there are any concerns.

**Comment by loneil** [comment]
Emailed back to shaun.bathgate@gov.bc.ca at _Wed 2020-12-23 11:19 AM_
