### ISSUE TITLE
GETOK Registration for GRAD - skarekks@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#250]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: GRAD <br /> IDIR: skarekks@idir <br /> Email: s.karekkattumanasreekumaran@cgi.com</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Added to existing GRAD team and email sent back to s.karekkattumanasreekumaran@cgi.com at _Thu 2021-01-14 9:33 AM_
