### ISSUE TITLE
GETOK Registration for PHSA_SALESFORCE - cwevans@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#254]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PHSA_SALESFORCE <br /> IDIR: cwevans@idir <br /> Email: christian.w.evans@gov.bc.ca</p> <p><strong>User comments:</strong><br/>For COVID-19 vaccine appointments by PHSA, managed through SalesForce.

**Comment by loneil** [comment]
Added Chris for this one as users don't have IDIRs yet
