### ISSUE TITLE
GETOK Registration for PSP - sookeke@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#255]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PSP <br /> IDIR: sookeke@idir <br /> Email: stanley.okeke@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Emailed back (from lucas.oneil@gov.bc.ca) stanley.okeke@gov.bc.ca at _Tue 2021-02-16 9:31 AM_
