### ISSUE TITLE
GETOK Registration for CSB_COA - tsemple@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#256]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CSB_COA <br /> IDIR: tsemple@idir <br /> Email: travis8814@gmail.com</p> <p><strong>User comments:</strong><br/>This is for the Ministry of Attorney General - Court Services Branch - Court of Appeal

**Comment by loneil** [comment]
Emailed back (from lucas.oneil@gov.bc.ca) travis8814@gmail.com at Tue 2021-02-16 11:29 AM_
