### ISSUE TITLE
GETOK Registration for CSB_COA - wbarnes@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#257]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CSB_COA <br /> IDIR: wbarnes@idir <br /> Email: wade.barnes@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Emailed back (from lucas.oneil@gov.bc.ca) wade.barnes@gov.bc.ca at Tue 2021-02-16 11:54 AM_
