### ISSUE TITLE
GETOK Registration for PIMS - lawrlau@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#265]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PIMS <br /> IDIR: lawrlau@idir <br /> Email: lawrence.lau@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Hi Lucas, I'd also like to have "admin" access to reset the ches password and other mgmt stuff. Could you also give access to sharala.perumal@gov.bc.ca and bruce.elder@gov.bc.ca as well?
Thanks!
Lawrence

**Comment by TimCsaky** [comment]
added Lawrence and Bruse and repled to them to confirm.
Still waiting for Sharala to confirm she has logged in to GETOK
