### ISSUE TITLE
GETOK Registration for CIT - bbeach@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#267]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CIT <br /> IDIR: bbeach@idir <br /> Email: brendan.beach@gov.bc.ca</p> <p><strong>User comments:</strong><br/>For Citizens' Services tool for community investment opportunities.

**Comment by loneil** [comment]
Created and emailed back to _brendan.beach@gov.bc.ca_ at _Tue 2021-04-06 3:25 PM_
