### ISSUE TITLE
GETOK Registration for CIT - zpez@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#268]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CIT <br /> IDIR: zpez@idir <br /> Email: zachary.pez@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
zpez added to existing CIT acronym and emailed back _Tue 2021-04-06 4:19 PM_
