### ISSUE TITLE
GETOK Registration for CIT - shermsen@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#269]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CIT <br /> IDIR: shermsen@idir <br /> Email: sarah.hermsen@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
shermsen added to existing CIT acronym and email back _Tue 2021-04-06 4:27 PM_
