### ISSUE TITLE
GETOK Registration for HCAP - wsonnex@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#273]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: HCAP <br /> IDIR: wsonnex@idir <br /> Email: will.sonnex@gov.bc.ca</p> <p><strong>User comments:</strong><br/>This is for the Health Career Access Program application.

**Comment by loneil** [comment]
HCAP created and wsonnex added, emailed back at _Mon 2021-05-10 10:39 AM_
