### ISSUE TITLE
GETOK Registration for BIOHUBBC - rstens@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#283]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: BIOHUBBC <br /> IDIR: rstens@idir <br /> Email: roland.stens@gov.bc.ca</p> <p><strong>User comments:</strong><br/>The source of BC’s species inventory data.

**Comment by loneil** [comment]
Approved and emailed back at _Fri 2021-05-21 9:42 AM_
