### ISSUE TITLE
GETOK Registration for BCTW - jrpopkin@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#284]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: BCTW <br /> IDIR: jrpopkin@idir <br /> Email: jamie.2.popkin@gov.bc.ca</p> <p><strong>User comments:</strong><br/>This account is for the BC Telemetry Warehouse.

**Comment by loneil** [comment]
Approved and emailed back _Fri 2021-05-21 12:53 PM_
