### ISSUE TITLE
GETOK Registration for BCTW - vchong@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#285]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: BCTW <br /> IDIR: vchong@idir <br /> Email: victor.chong@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Access request for the BC Telemetry Warehouse. Our system sends e-mails to stakeholders for verification during onboarding and to notify them of data alerts and system events.

**Comment by loneil** [comment]
Added to acronym and emailed back _Fri 2021-05-21 4:47 PM_
