### ISSUE TITLE
GETOK Registration for TRACKS - vchong@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#286]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: TRACKS <br /> IDIR: vchong@idir <br /> Email: victor.chong@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Access request for the Tenured Recreational Activity on Crownland Knowledge System (Tracks). Our system sends e-mails to stakeholders for verification during onboarding and to notify them when reports are due and processed.

**Comment by loneil** [comment]
Acronym created and emailed back _Fri 2021-05-21 4:49 PM_
