### ISSUE TITLE
GETOK Registration for WTRP_INFO - emiles@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#290]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: WTRP_INFO <br /> IDIR: emiles@idir <br /> Email: escher.miles@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Notices for the NRM Refresh Project

**Comment by cwevans** [comment]
The client does not require access to APIs hosted by the Common Services Showcase team and is asking for permission to view the Common Hosted Email Service (CHES) Showcase application. The CHES demo app does not require a GETOK token for access. 

Informed client how to access CHES Showcase and this issue can be closed without action.
