### ISSUE TITLE
GETOK Registration for OPTIMIZE - pplatten@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#291]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: OPTIMIZE <br /> IDIR: pplatten@idir <br /> Email: peter.platten@gov.bc.ca</p> <p><strong>User comments:</strong><br/>This is an account the OPTIMIZE team will use to send storage notification emails to NRM users.

**Comment by TimCsaky** [comment]
user added to acronym and notified
