### ISSUE TITLE
GETOK Registration for OPTIMIZE - hhay@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#292]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: OPTIMIZE <br /> IDIR: hhay@idir <br /> Email: heather.hay@gov.bc.ca</p> <p><strong>User comments:</strong><br/>please add me to the client account named OPTIMIZE for testing

**Comment by TimCsaky** [comment]
user added to acronym and notified
