### ISSUE TITLE
GETOK Registration for ZEVA - rtan@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#295]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: ZEVA <br /> IDIR: rtan@idir <br /> Email: richard.tan@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by TimCsaky** [comment]
Richard has been given access to ZEVA appp in GetOK. and he was notified.
