### ISSUE TITLE
GETOK Registration for WORKBC_FORMS - rsolorza@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#300]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: WORKBC_FORMS <br /> IDIR: rsolorza@idir <br /> Email: rafael.solorzano@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by TimCsaky** [comment]
Acronym: WORKBC_FORMS
IDIR: rsolorza@idir 

access registered. client notified (rafael.solorzano@gov.bc.ca)
