### ISSUE TITLE
GETOK Registration for MAP_AGOL_CAR - dareboss@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#302]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: MAP_AGOL_CAR <br /> IDIR: dareboss@idir <br /> Email: darren.boss@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by jujaga** [comment]
Approved and notified on 9/17/2021.
