### ISSUE TITLE
GETOK Registration for FEEDBC_DIR - smhoward@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#304]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: FEEDBC_DIR <br /> IDIR: smhoward@idir <br /> Email: steve.m.howard@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Email service for the Feed BC Directory

**Comment by loneil** [comment]
Approved and emailed _steve.m.howard@gov.bc.ca_ back _Tue 2021-10-12 4:22 PM_
