### ISSUE TITLE
GETOK Registration for APPS_ITSM - cdb27059af1645f8b42a11bdc823ee9d@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#306]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: APPS_ITSM <br /> IDIR: cdb27059af1645f8b42a11bdc823ee9d@idir <br /> Email: zhibin.su@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Closing, didn't hear back about IDIR issue
