### ISSUE TITLE
GETOK Registration for FOI_REQUESTS - jadsaad@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#309]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: FOI_REQUESTS <br /> IDIR: jadsaad@idir <br /> Email: jad.saad@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Requesting this for the receipt generation of the payment integration

**Comment by loneil** [comment]
Approved and emailed jad.saad@gov.bc.ca back Mon 2021-11-01 1:11 PM
