### ISSUE TITLE
GETOK Registration for REALM_REGISTRY - juahn@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#312]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: REALM_REGISTRY <br /> IDIR: juahn@idir <br /> Email: junmin.ahn@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Acronym created and user _juahn_ emailed back _Thu 2021-11-04 10:33 AM_
