### ISSUE TITLE
GETOK Registration for CSB_RG - tsemple@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#315]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CSB_RG <br /> IDIR: tsemple@idir <br /> Email: travis8814@gmail.com</p> <p><strong>User comments:</strong><br/>Representation Grant (Probate)

**Comment by loneil** [comment]
Acronym created morning 2021-11-22
