### ISSUE TITLE
GETOK Registration for EHPR - dbayly@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#316]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: EHPR <br /> IDIR: dbayly@idir <br /> Email: dbayly@freshworks.io</p> <p><strong>User comments:</strong><br/>

**Comment by loneil** [comment]
Acronym created and user emailed back _Mon 2021-11-22 11:14 AM_
