### ISSUE TITLE
GETOK Registration for PSA_DIGITAL_JOURNEYS - ssmaaber@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#331]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PSA_DIGITAL_JOURNEYS <br /> IDIR: ssmaaber@idir <br /> Email: simen@freshworks.io</p> <p><strong>User comments:</strong><br/>

**Comment by TimCsaky** [comment]
acronym PSA_DIGITAL created. 
client informed. asked to contact us if they want a different acronym
