### ISSUE TITLE
GETOK Registration for PIDP - vvella@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#332]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PIDP <br /> IDIR: vvella@idir <br /> Email: virginia.vella@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by jujaga** [comment]
Approved `vvella` to new `PIDP` acronym.
