### ISSUE TITLE
GETOK Registration for EMBCESS - yossit@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#335]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: EMBCESS <br /> IDIR: yossit@idir <br /> Email: yossi.1.tamari@gov.bc.ca</p> <p><strong>User comments:</strong><br/>We're looking into replacing our current PDF generator which is based on Puppeteer with CDogs.

Thanks!

**Comment by TimCsaky** [comment]
Acronym EMBCESS created, Yossi notified
