### ISSUE TITLE
GETOK Registration for WPS - cbrady@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#338]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: WPS <br /> IDIR: cbrady@idir <br /> Email: conor.brady@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Wildfire Predictive Services document generator account

**Comment by TimCsaky** [comment]
I've asked Connor to choose a different acronym as WPS is already in IRS

**Comment by TimCsaky** [comment]
he's suggested 'WPS_HFI'

**Comment by TimCsaky** [comment]
acronym created, emailed client
