### ISSUE TITLE
GETOK Registration for FEEDBC_DIR - sturple@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#343]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: FEEDBC_DIR <br /> IDIR: sturple@idir <br /> Email: shawn.turple@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by TimCsaky** [comment]
Shawn added to application and notified
