### ISSUE TITLE
GETOK Registration for CLIMATE_FUND - sturple@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#344]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CLIMATE_FUND <br /> IDIR: sturple@idir <br /> Email: shawn.turple@gov.bc.ca</p> <p><strong>User comments:</strong><br/>This is for using the cdogs api

**Comment by TimCsaky** [comment]
client added to the new acronym and notified
