### ISSUE TITLE
GETOK Registration for CLIMATE_FUND - smhoward@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#345]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CLIMATE_FUND <br /> IDIR: smhoward@idir <br /> Email: steve.m.howard@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Another application within our team.

**Comment by TimCsaky** [comment]
client added to the acronym and notified
