### ISSUE TITLE
GETOK Registration for CLIMATE_FUND - crrobert@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#346]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CLIMATE_FUND <br /> IDIR: crrobert@idir <br /> Email: craig.robertson@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by TimCsaky** [comment]
client added to the acronym and notified
