### ISSUE TITLE
GETOK Registration for CRROBERT_LOCLDEV - crrobert@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#350]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CRROBERT_LOCLDEV <br /> IDIR: crrobert@idir <br /> Email: craig.robertson@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by TimCsaky** [comment]
Advised Robert to choose a more official, project specific acronym, because we cant maintain test, disposable service clients
Robert has decided not to register an acronym at this time.
no service client or db record created. Robert notified.
