### ISSUE TITLE
GETOK Registration for SERVEBC - srestall@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#353]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: SERVEBC <br /> IDIR: srestall@idir <br /> Email: sylvia.restall@gov.bc.ca</p> <p><strong>User comments:</strong><br/>This is for the  ServeLegalDocuments new system

**Comment by TimCsaky** [comment]
done
