### ISSUE TITLE
GETOK Registration for OSPG - srestall@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#354]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: OSPG <br /> IDIR: srestall@idir <br /> Email: sylvia.restall@gov.bc.ca</p> <p><strong>User comments:</strong><br/>This is for the  Office of the Superintendent of Professional Governance new system

**Comment by TimCsaky** [comment]
done
