### ISSUE TITLE
GETOK Registration for ZEVA - sashidas@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#359]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: ZEVA <br /> IDIR: sashidas@idir <br /> Email: sashi.das@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Looking to understand more about the ZEVA application

**Comment by slhurley** [comment]
Rejecting this request as this is a DA not a Developer.
