### ISSUE TITLE
GETOK Registration for CHEFS - akusumba@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#365]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CHEFS <br /> IDIR: akusumba@idir <br /> Email: anurag.kusumba@gov.bc.ca</p> <p><strong>User comments:</strong><br/>

**Comment by slhurley** [comment]
CANCELLED...this is not a valid request as CHEFS is not an app acronym.
