### ISSUE TITLE
GETOK Registration for NROG - cmeng@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#372]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: NROG <br /> Ministry: Ministry of Land, Water and Resource Stewardship <br /> IDIR: cmeng@idir <br /> Email: catherine.meng@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Hello there, Hope everything is going well! We are working on a project called Old Growth, and would like to be able to send email with attachment in our app using the api service. Thanks and have a great day!

**Comment by slhurley** [comment]
Request complete
