### ISSUE TITLE
GETOK Registration for CHEFS - zbhunnoo@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#376]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CHEFS <br /> Ministry: Forest <br /> IDIR: zbhunnoo@idir <br /> Email: ziad.bhunnoo@gov.bc.ca</p> <p><strong>User comments:</strong><br/>I am using CHEFS

**Comment by slhurley** [comment]
This request will not be fulfilled...GETOK not required to use CHEFS
