### ISSUE TITLE
GETOK Registration for MOD_AT_TEST - atees@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#382]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: MOD_AT_TEST <br /> Ministry: Citizens' Services <br /> IDIR: atees@idir <br /> Email: arlen.tees@gov.bc.ca</p> <p><strong>User comments:</strong><br/>I'm on the Modernization Acceleration team within the Digital Office (formerly Digital and Data Platforms Division), and this is simply test the Common Hosted Forms locally

**Comment by TimCsaky** [comment]
service client MOD_AT created, client notified
