### ISSUE TITLE
GETOK Registration for FOI_EMAIL_REQS - asobha@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#386]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: FOI_EMAIL_REQS <br /> Ministry: Ministry of Citizen Services <br /> IDIR: asobha@idir <br /> Email: aparna.sobha@gov.bc.ca</p> <p><strong>User comments:</strong><br/>FOI_EMAIL_REQS : FOI Email Requests
We will be using Common Hosted Email Service

**Comment by slhurley** [comment]
This request is for CHES (the other older FOI_REQUESTS was for CDOGS)

**Comment by slhurley** [comment]
Subsequently revoked in favor of FOI_REQUESTS
