### ISSUE TITLE
GETOK Registration for ALCS - acharbon@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#390]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: ALCS <br /> Ministry: Agriculture and Food <br /> IDIR: acharbon@idir <br /> Email: ansley.charbonneau@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Agricultural Land Commission System, will be using COMS, CDOGS, CHES

**Comment by TimCsaky** [comment]
service client created and client notified through getok admin feature.
