### ISSUE TITLE
GETOK Registration for MET - sxazhiko@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#391]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: MET <br /> Ministry: Environmental Assessment Office <br /> IDIR: sxazhiko@idir <br /> Email: saravan.azhikoden@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Modern Engagement Tool
Common service Used - CHES

**Comment by slhurley** [comment]
Access granted...will be CHES used from BCGov OpenShift.
