### ISSUE TITLE
GETOK Registration for MET - sxazhiko@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#392]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: MET <br /> Ministry: BC Environmental Assessment Office <br /> IDIR: sxazhiko@idir <br /> Email: saravan.azhikoden@gov.bc.ca</p> <p><strong>User comments:</strong><br/>MET - Modern Engagement tool
Planning to use CHES .

**Comment by slhurley** [comment]
Duplicate
