### ISSUE TITLE
GETOK Registration for PST_ALERTS - ianwatts@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#393]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PST_ALERTS <br /> Ministry: Citizen Services <br /> IDIR: ianwatts@idir <br /> Email: ian.1.watts@gov.bc.ca</p> <p><strong>User comments:</strong><br/>PST = Platform Services Team of the DevExchange
This account will be used for emailing automated alerts to the team.

**Comment by slhurley** [comment]
Approved and processed.
