### ISSUE TITLE
GETOK Registration for REGISTRY - billyli@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#394]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: REGISTRY <br /> Ministry: Citizen Services <br /> IDIR: billyli@idir <br /> Email: billy.li@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Platform Services Registry

**Comment by TimCsaky** [comment]
cancelled. not required by client
