### ISSUE TITLE
GETOK Registration for PS_REG - billyli@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#395]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: PS_REG <br /> Ministry: Citizens' Sercives <br /> IDIR: billyli@idir <br /> Email: billy.li@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Platform Services Registry

**Comment by TimCsaky** [comment]
team member added to client PS_REG
