### ISSUE TITLE
GETOK Registration for CHEFS - jachung@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#398]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CHEFS <br /> Ministry: Citizens' Services <br /> IDIR: jachung@idir <br /> Email: jason.chung@gov.bc.ca</p> <p><strong>User comments:</strong><br/>We're using CHES to notify users and CDOGS to generate forms.

**Comment by loneil** [comment]
Forminators team member added to CHEFS
