### ISSUE TITLE
GETOK Registration for CHEFS - aidowu@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#399]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: CHEFS <br /> Ministry: Citizen Services <br /> IDIR: aidowu@idir <br /> Email: ayobamii.idowu@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Common Hosted Forms Services

**Comment by loneil** [comment]
Forminators team member added to CHEFS
