### ISSUE TITLE
GETOK Registration for GDX_AGTTRACKER - sturple@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#400]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: GDX_AGTTRACKER <br /> Ministry: Citizens' Services <br /> IDIR: sturple@idir <br /> Email: shawn.turple@gov.bc.ca</p> <p><strong>User comments:</strong><br/>GDX - Government Digital Experience Division Agreements Tracker

**Comment by slhurley** [comment]
Granted as AGTTRACKER rather than GDX_AGTTRACKER.
