### ISSUE TITLE
GETOK Registration for POWER_AUTOMATE - tobright@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#401]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: POWER_AUTOMATE <br /> Ministry: LWRS <br /> IDIR: tobright@idir <br /> Email: tom.obright@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Determining how to encapsulate the CHES API into a Microsoft Power Automate Custom Connector for use in Power Automate flows.

**Comment by slhurley** [comment]
Closing this request as they will be going with Exchange Online instead from Dynamics 365.
