### ISSUE TITLE
GETOK Registration for EPHR - nisamson@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#404]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: EPHR <br /> Ministry: Health <br /> IDIR: nisamson@idir <br /> Email: nino.samson@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Can you please add me as contact for EHPR and transfer ownership of keys to me?

**Comment by slhurley** [comment]
Team member added
