### ISSUE TITLE
Cannot use CHES from local dev environment

### ISSUE THREAD

**Issue by KillianFaussart** [bcgov/nr-get-token#405]
#### Describe the bug
Hi team. We are working with the Common Components team at the Ministry of Citizen Services and our developers are running into an issue where they cannot access the service from their local environment. They keep getting a 401 Unauthorized. It's been challenging to understand why but maybe you can help us figure out what could be happening. 
(Our team is within the Gov network)

Thank you for your help. :) 

#### To Reproduce
N/A

#### Expected behavior
N/A
#### Screenshots
N/A

#### Desktop (please complete the following information):

- OS: Windows 10

#### Smartphone (please complete the following information):
N/A

**Comment by TimCsaky** [comment]
Hey Killian.
There are a few different factors that might affect access.
If you have Rocket Chat, you can also contact us in the #nr-common-services-showcase channel.
a 401 sounds like your access token for calling the API is not valid.

**Comment by KillianFaussart** [comment]
> Hey Killian. There are a few different factors that might affect access. If you have Rocket Chat, you can also contact us in the #nr-common-services-showcase channel. a 401 sounds like your access token for calling the API is not valid.

Thank you very much for the reply. We will contact the team in Rocket Chat to get some help. :)
