### ISSUE TITLE
GETOK Registration for DIO_COCO_ASSESS - shphilli@idir

### ISSUE THREAD

**Issue by bcgov-nr-csst** [bcgov/nr-get-token#411]
<p>Request from GETOK for acronym creation/access</p> <p>Acronym: DIO_COCO_ASSESS <br /> Ministry: OCIO <br /> IDIR: shphilli@idir <br /> Email: shea.phillips@gov.bc.ca</p> <p><strong>User comments:</strong><br/>Experimenting with generating documents to support DIO Common Component funding process.

**Comment by slhurley** [comment]
Approved for CITZ Common Components team Financial Assess
